services:
  - type: redis
    name: or-prod-redis
    plan: free
    ipAllowList: []

  - type: web
    name: or-prod-backend
    env: python
    plan: free
    envVars: 
      - key: PYTHON_VERSION
        value: 3.10.11
    repo: https://github.com/Simplyalex99/OpenReview.git
    buildCommand: cd ./backend && pip3 install -r requirements.txt --filter=backend
    startCommand: cd ./backend && gunicorn run:app
    buildFilter:
      paths:
        - backend/**

  - type: web
    env: node
    name: or-prod-frontend
    plan: free
    repo: https://github.com/Simplyalex99/OpenReview.git
    buildCommand: cd ./frontend && npm run build --filter=frontend
    startCommand: cd./frontend && npm run start
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: NEXT_PUBLIC_API_HOST
        fromService: 
          name: or-prod-backend
          type: web
          property: host
